### ISSUE TITLE
🎲 2020-09-09-Meeting

### ISSUE THREAD

**Issue by youngroklee323** [hapas-io/hyupup#10]
**⏰ 이 회의록은 YYYY-MM-DD 에 정리될 예정입니다!**

TODO
- [x] Slack 정기회의용 채널생성
- [x] 캘린더 일정 생성

**Comment by youngroklee323** [comment]
2D에서 쓰듯이 그게 조금더 그냥 볼륨감있게 만든 것 뿐이다
나도 그렇게 생각한게, 우리가 언어나 이미지 등등의 정보가 2D이기 때문에 깊이라는 새로운 축을 쥐어줘도, 2D에서 크게 벗어나지 않음.
문서화 작업자체가 어려운데, 이러한 작업을 Ai가 자동으로 문서화 해줌 그리고 자동적으로 키워드를 만들거나, ai를 활용해서검색이 쉬워진다.
AR에서는 현실과 정보의 연계성, 연결성 현실에서 정보로 오는 중간과정이 없이. 직관적인 정보제공에 용이하다.

종이에서 todo를 하던시절에서 앱으로 todo로 넘어왔듯이, 깊이감 있는 AR또한 새로운 레이아웃에 적응 할 사람들이 있을것이며, 그렇기에 깊이감있는 AR은 단순히 환상으로 보기는 어렵다.
Z축이 생김에 따라 남들보다 더 많은 정보를 빠르게 정리가 가능하다면, 충분히 메리트가 있을것.

이영록이 삼멤에 필요한 ui를 디자인하면 한상현이 코딩으로 구현하자

전체적인 서비스를 만드는것 말고 ui하나 하나 작은단위를 만들고 그 과정을 남기자

**Comment by Hansanghyeon** [comment]
> 전체적인 서비스를 만드는것 말고 ui하나 하나 작은단위를 만들고 그 과정을 남기자

😤 UI/UX를 통해서 협업을 경험해보고 숙련 해보자!

둘다 흥미로운 뜻으로 hyupup을 시작하였는데 서비스를 제작하려다 보니까 UI/UX 말고도 신경 써야 할 것들이 너무 많아 졌습니다 😓
그래서 쉬엄쉬엄 사이드로 서로 피드백이오고가고 의견을 주고 받는 것을 최우선으로 하기위해서 서비스가아닌 UI/UX로만 접근해서 진행하기로 땅땅땅 👏

### Quest
@youngroklee323 
- [ ] 삼멤 하나의 UI가 완료되면 UI관련된 내용 적어서 [Link 저장소](https://github.com/hapas-io/hyupup-storybook/issues) 이슈 생성

@Hansanghyeon 
- [ ] 삼멤 UI 나오기전에 [키오스크 UI](https://xd.adobe.com/view/5028e134-9d45-4f68-b691-b4746f91727a-057b/screen/9d10b08a-1344-4dc5-9425-0f6c52f6cded) 참고해서 UI 이슈 제작
